# https://www.codewars.com/kata/return-the-latest-modified-file/train/shell
# My solution
ls -t1 | head -1
# ...
ls -t | head -1
# ...
ls -t | head -n 1
# ...
ls -ltr | tail -1 | awk '{print $NF}'
# ...
ls -t $1 | sed -n 1p
# ...
ls -lt | awk '{print $9}' | sed -n '2p'
# ...
array=($(ls -t))
echo ${array[0]}
# ...
ls -t | awk 'NR==1 { print }' 
# ...
echo  `ls -tp | grep -v /$ | head -1`
