# https://www.codewars.com/kata/reverser/train/shell
# My solution
echo $(echo $1 | rev) | bc -l
# ...
echo "$1" | rev | bc
# ...
echo $((10#`echo $1 | rev`))
# ...
echo $1 | rev | sed 's/^0\+//'
# ...
aux=`echo $1|rev`
expr $aux + 0
# ...
echo $1 | rev | egrep -o "[^0]+.+"
# ...
input=$1
echo $input | rev | sed 's/^0*//'